using System.Text;
using System.Text.RegularExpressions;

namespace CopilotNexus.DevAssistant;

/// <summary>
/// Creates and manages issue markdown files in the docs/issues/ directory.
/// </summary>
internal sealed class IssueManager
{
    private readonly string _issueDirectory;
    private readonly ILogger<IssueManager> _logger;

    public IssueManager(string issueDirectory, ILogger<IssueManager> logger)
    {
        _issueDirectory = issueDirectory;
        _logger = logger;
    }

    /// <summary>
    /// Creates an issue markdown file from a detected log entry. Returns the file path.
    /// </summary>
    public string CreateIssue(LogEntry entry)
    {
        Directory.CreateDirectory(_issueDirectory);

        var slug = GenerateSlug(entry.Message);
        var timestamp = entry.TimestampUtc.ToString("yyyyMMdd-HHmmss");
        var fileName = $"{timestamp}-{slug}.md";
        var filePath = Path.Combine(_issueDirectory, fileName);

        // Avoid overwriting if file already exists (race condition guard)
        if (File.Exists(filePath))
        {
            _logger.LogDebug("Issue file already exists: {File}", fileName);
            return filePath;
        }

        var content = FormatIssueMarkdown(entry, fileName);
        File.WriteAllText(filePath, content, Encoding.UTF8);

        _logger.LogInformation("Created issue: {File}", fileName);
        return filePath;
    }

    /// <summary>
    /// Returns all issue files with their parsed metadata.
    /// </summary>
    public List<IssueSummary> ListIssues(string? statusFilter = null)
    {
        if (!Directory.Exists(_issueDirectory))
            return [];

        var issues = new List<IssueSummary>();
        foreach (var file in Directory.GetFiles(_issueDirectory, "*.md").OrderByDescending(f => f))
        {
            var summary = ParseIssueSummary(file);
            if (summary != null && (statusFilter == null || summary.Status.Equals(statusFilter, StringComparison.OrdinalIgnoreCase)))
                issues.Add(summary);
        }

        return issues;
    }

    /// <summary>
    /// Updates the status of an issue file from "open" to "resolved".
    /// </summary>
    public bool ResolveIssue(string fileName)
    {
        var filePath = Path.Combine(_issueDirectory, fileName);
        if (!File.Exists(filePath)) return false;

        var content = File.ReadAllText(filePath);
        var updated = content.Replace("**Status:** open", "**Status:** resolved");
        if (updated == content) return false; // already resolved or format mismatch

        File.WriteAllText(filePath, updated, Encoding.UTF8);
        _logger.LogInformation("Resolved issue: {File}", fileName);
        return true;
    }

    /// <summary>
    /// Loads existing issue hashes so the log watcher can skip duplicates.
    /// </summary>
    public HashSet<string> LoadExistingIssueHashes()
    {
        var hashes = new HashSet<string>();
        if (!Directory.Exists(_issueDirectory)) return hashes;

        foreach (var file in Directory.GetFiles(_issueDirectory, "*.md"))
        {
            var summary = ParseIssueSummary(file);
            if (summary is { Status: "open" })
            {
                // Reconstruct the hash from the stored metadata
                if (!string.IsNullOrEmpty(summary.IssueHash))
                    hashes.Add(summary.IssueHash);
            }
        }

        return hashes;
    }

    private static string FormatIssueMarkdown(LogEntry entry, string fileName)
    {
        var title = ExtractTitle(entry.Message);
        var issueHash = LogWatcherService.ComputeIssueHash(entry.Component, entry.Severity, entry.Message);
        var contextBlock = string.Join("\n", entry.ContextLines);

        return $"""
            # {title}

            **Component:** {entry.Component}
            **Severity:** {entry.Severity}
            **Timestamp:** {entry.TimestampUtc:O}
            **File:** {entry.FileName}:{entry.LineNumber}
            **Status:** open
            **Hash:** {issueHash}

            ## Log Excerpt

            ```log
            {contextBlock}
            ```

            ## Suggested Fix Prompt

            ```text
            I have a {entry.Severity.ToLowerInvariant()} in the {entry.Component} component of Copilot Nexus.

            The error occurred at {entry.TimestampUtc:O} in log file {entry.FileName}:

            {entry.Message}

            Context:
            {contextBlock}

            Please analyze this error, identify the root cause, and suggest a fix. Check the relevant source
            files in the src/ directory for the {entry.Component} component.
            ```

            ## Notes

            _Auto-generated by DevAssistant on {DateTimeOffset.UtcNow:O}_
            """;
    }

    private static string ExtractTitle(string logMessage)
    {
        // Strip timestamp and severity prefix to get a meaningful title
        var stripped = Regex.Replace(logMessage,
            @"^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:\s?(?:Z|[+\-]\d{2}:\d{2}))?\s+\[[A-Z]{3}\]\s*",
            "");

        // Truncate to a reasonable title length
        if (stripped.Length > 100)
            stripped = stripped[..100];

        return stripped.Trim();
    }

    private static string GenerateSlug(string message)
    {
        var title = ExtractTitle(message).ToLowerInvariant();
        var slug = Regex.Replace(title, @"[^a-z0-9]+", "-").Trim('-');
        if (slug.Length > 60) slug = slug[..60].TrimEnd('-');
        return string.IsNullOrEmpty(slug) ? "unknown-issue" : slug;
    }

    internal static IssueSummary? ParseIssueSummary(string filePath)
    {
        try
        {
            var lines = File.ReadLines(filePath).Take(10).ToList();
            var title = lines.FirstOrDefault(l => l.StartsWith("# "))?.TrimStart('#', ' ') ?? "Unknown";
            var component = ExtractField(lines, "Component");
            var severity = ExtractField(lines, "Severity");
            var timestamp = ExtractField(lines, "Timestamp");
            var status = ExtractField(lines, "Status");
            var hash = ExtractField(lines, "Hash");

            return new IssueSummary(
                Path.GetFileName(filePath),
                title,
                severity ?? "Unknown",
                component ?? "Unknown",
                timestamp ?? "",
                status ?? "open",
                hash ?? "");
        }
        catch
        {
            return null;
        }
    }

    private static string? ExtractField(List<string> lines, string fieldName)
    {
        var prefix = $"**{fieldName}:**";
        var line = lines.FirstOrDefault(l => l.StartsWith(prefix));
        return line?.Substring(prefix.Length).Trim();
    }
}

internal sealed record IssueSummary(
    string FileName,
    string Title,
    string Severity,
    string Component,
    string Timestamp,
    string Status,
    string IssueHash);
